title: Cardano Documentation
email: cardano@iohk.io
description: Documentation for the Cardano Project
baseurl: ""
url: "https://docs.cardano.org"
include: ["_pages","_docs", "_data"]
permalink: /:title

markdown: kramdown
highlighter: rouge
array: []
